#!/usr/bin/env node
/*
 * Downloads every font from scripts/fonts.config.js via `npm pack`
 * (Fontsource packages, SIL Open Font License), keeps only the Cyrillic
 * and Latin WOFF2 subsets and generates:
 *   assets/fonts/<id>/*.woff2 + LICENSE
 *   assets/css/fonts.css      — @font-face rules (files load only when used)
 *   assets/js/fonts-data.js   — metadata for the interface
 * Usage: node scripts/fetch-fonts.js
 */
"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const FONTS_DIR = path.join(ROOT, "assets/fonts");
const SUBSETS = ["cyrillic", "latin"];
const config = require("./fonts.config.js");

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "fonts-"));
let css = "/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\n";
const data = [];

function cssFilesFor(font) {
  if (!font.variable) {
    return font.weights.flatMap(w => [`${w}.css`].concat(font.italic ? [`${w}-italic.css`] : []));
  }
  const axis = font.axisFile || "wght"; // e.g. "opsz" = files with opsz + wght axes
  return [axis + ".css"].concat(font.italic ? [axis + "-italic.css"] : []);
}

for (const font of config) {
  process.stdout.write(`• ${font.family} … `);
  let out;
  try {
    out = execSync(`npm pack ${font.pkg} --silent`, { cwd: tmp, stdio: ["ignore", "pipe", "ignore"] }).toString().trim().split("\n").pop();
  } catch (e) { console.log("SKIPPED: package not found"); continue; }
  const dir = path.join(tmp, font.id);
  fs.mkdirSync(dir, { recursive: true });
  execSync(`tar xzf "${path.join(tmp, out)}" -C "${dir}"`);
  const pkgDir = path.join(dir, "package");
  const dest = path.join(FONTS_DIR, font.id);
  fs.rmSync(dest, { recursive: true, force: true });
  fs.mkdirSync(dest, { recursive: true });
  if (fs.existsSync(path.join(pkgDir, "LICENSE"))) fs.copyFileSync(path.join(pkgDir, "LICENSE"), path.join(dest, "LICENSE"));

  let count = 0, cyr = 0, fontCss = "";
  for (const file of cssFilesFor(font)) {
    if (!fs.existsSync(path.join(pkgDir, file))) continue;
    const src = fs.readFileSync(path.join(pkgDir, file), "utf8");
    const blocks = src.match(/@font-face\s*{[^}]+}/g) || [];
    for (const block of blocks) {
      const m = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/);
      if (!m) continue;
      const fname = m[1];
      const subset = SUBSETS.find(s => fname.includes(`-${s}-`) && !fname.includes(`-${s}-ext-`));
      if (!subset) continue;
      fs.copyFileSync(path.join(pkgDir, "files", fname), path.join(dest, fname));
      const fmt = font.variable ? "woff2-variations" : "woff2";
      if (subset === "cyrillic") cyr++;
      fontCss += "\n" + block
        .replace(/font-family:\s*'[^']+'/, `font-family: '${font.family}'`)
        .replace(/src:[^;]+;/, `src: url(../fonts/${font.id}/${fname}) format('${fmt}');`) + "\n";
      count++;
    }
  }
  if (!cyr) { fs.rmSync(dest, { recursive: true, force: true }); console.log("SKIPPED: no Cyrillic subset"); continue; }
  css += fontCss;
  const { pkg, axisFile, ...meta } = font;
  data.push(meta);
  console.log(`${count} files`);
}

fs.writeFileSync(path.join(ROOT, "assets/css/fonts.css"), css);
fs.writeFileSync(
  path.join(ROOT, "assets/js/fonts-data.js"),
  "/* Generated by scripts/fetch-fonts.js — do not edit by hand. */\nwindow.FONTS = " + JSON.stringify(data, null, 2) + ";\n"
);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`Done: ${data.length} families.`);
